"""Recreate migrations

Revision ID: 36f04e187f12
Revises: 
Create Date: 2024-11-11 21:16:16.412317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f04e187f12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade() -> None:
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=True),
            sa.Column('document', sa.String(), nullable=True),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('user_type', sa.String(), nullable=True),
            sa.Column('file', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('document'),
            sa.UniqueConstraint('email'),
        )
        op.create_table(
            'images',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('image_data', sa.Text(), nullable=True),
            sa.Column('category', sa.String(), nullable=True),
            sa.Column('subcategory', sa.String(), nullable=True),
            sa.Column('description', sa.String(length=500), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_table(
            'image_ratings',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('evaluator_id', sa.Integer(), nullable=True),
            sa.Column('image_id', sa.Integer(), nullable=True),
            sa.Column('rating', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['evaluator_id'], ['users.id']),
            sa.ForeignKeyConstraint(['image_id'], ['images.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_table(
            'tokens',
            sa.Column('token', sa.String(), nullable=False),
            sa.Column('used', sa.Boolean(), nullable=True),
            sa.Column('expiration_date', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('token'),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
